use master
go

drop database if exists rwatson31_tugOwar
go

create database rwatson31_tugOwar
go

ALTER DATABASE rwatson31_tugOwar SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC rwatson31_tugOwar.[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE rwatson31_tugOwar SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE rwatson31_tugOwar SET ANSI_NULLS OFF 
GO
ALTER DATABASE rwatson31_tugOwar SET ANSI_PADDING OFF 
GO
ALTER DATABASE rwatson31_tugOwar SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE rwatson31_tugOwar SET ARITHABORT OFF 
GO
ALTER DATABASE rwatson31_tugOwar SET AUTO_CLOSE OFF 
GO
ALTER DATABASE rwatson31_tugOwar SET AUTO_SHRINK OFF 
GO
ALTER DATABASE rwatson31_tugOwar SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE rwatson31_tugOwar SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE rwatson31_tugOwar SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE rwatson31_tugOwar SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE rwatson31_tugOwar SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE rwatson31_tugOwar SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE rwatson31_tugOwar SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE rwatson31_tugOwar SET  ENABLE_BROKER 
GO
ALTER DATABASE rwatson31_tugOwar SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE rwatson31_tugOwar SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE rwatson31_tugOwar SET TRUSTWORTHY OFF 
GO
ALTER DATABASE rwatson31_tugOwar SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE rwatson31_tugOwar SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE rwatson31_tugOwar SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE rwatson31_tugOwar SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE rwatson31_tugOwar SET RECOVERY FULL 
GO
ALTER DATABASE rwatson31_tugOwar SET  MULTI_USER 
GO
ALTER DATABASE rwatson31_tugOwar SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE rwatson31_tugOwar SET DB_CHAINING OFF 
GO
ALTER DATABASE rwatson31_tugOwar SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE rwatson31_tugOwar SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE rwatson31_tugOwar SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE rwatson31_tugOwar SET QUERY_STORE = OFF
GO
USE rwatson31_tugOwar
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

drop table if exists gameState
go
CREATE TABLE [dbo].[gameState](
	[GameId] [varchar](9)
        CHECK (GameId like '[0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9][0-9]')
		CONSTRAINT UPKCL_gameId PRIMARY KEY CLUSTERED,

    player1Name       varchar(20)       NOT NULL,
	player2Name		varchar(20) not null,
	currentLocation       int       NOT NULL,
	currentTurns          int          NOT NULL

)